[package]
name = "ticker"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
structopt = { version = "0.3", default-features = false}
time = "0.3.37"
tokio = "1.44.2"
yahoo_finance_api = "2.4.0"
