[package]
name = "ticker"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
structopt = { version = "0.3", default-features = false}
time = "0.3.36"
tokio = "1.41.0"
yahoo_finance_api = "2.3.0"
